### ISSUE TITLE
FR: delete a session

### ISSUE THREAD

**Issue by rubaboo** [davestewart/workflowy-multiflow#10]
Please add the functionality. In the meantime, could you explain how to edit the saved sessions manually. I tried to follow instructions on the web about editing extensions' Local Storage, but wasn't able to locate the session list that I could edit or clear. Thank you!

**Comment by davestewart** [comment]
Hello,

You can delete sessions by hovering over the session and clicking the x:

<img width="510" alt="image" src="https://github.com/user-attachments/assets/e91e3f6b-2982-4c18-a4ae-5ec16476ad7a">

To update a session, change the options then click the Update Session button:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/2b7f8e07-2499-467c-aff1-25beed677e0d">

I don't think I advised anywhere to edit local storage, as it would be quite laborious to do manually.
